imports:
    - { resource: parameters.yml }

twig:
    form:
        resources:
            - 'CanalTPLieuIdealProductBundle:Form:fields.html.twig'
            - 'CanalTPLieuIdealCoreBundle:Form:fields.html.twig'
