imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }
swiftmailer:
    transport:  smtp
    auth_mode:  login
    host:       smtp.canaltp.fr
    username:   thomas.chevily.externe@canaltp.fr
    password:   Wxcv05*
    port:       25

#canal_tp_lieu_ideal_core:
#    webservices:
#        navitia: 'http://bordeaux.prod.navitia.com/cgi-bin/gwnavitia.dll'