canal_tp_lieu_ideal_core:
    webservices:
        navitia: 'default'
        enable_logs: true
    autocomplete: ~
    isochron:
        #  Nombre de points maximum affichés (stoparea)
        max_points: 2300
    #    Nombre de zones
        nbre_areas: 3
        ideal_minutes_adjustment: 10
    #    Temps de trajet maximum pour la dernière zone
        max_duration: 5800
    #    Temps maximum d'une zone
        max_areas_duration: 1800
    #    Active/désactive le module isochron
        active: true
        #    Nombre de zones
        nbre_areas: 5
        #    Temps de trajet maximum pour la dernière zone
        max_duration: 5800
         #    Active/désactive le module isochron
        active: true
    bestpoint:
    #  Nombre de points maximum affichés (stoparea)
        max_points: 2300
    #    Active/désactive le module bestpoint
        active: true
    #   Nombre de points idéal pour une rencontre
        nbre_points : 3
    gMap:
        zoom: 6
        center:
            lat:  46.52863469527167
            lon:  2.43896484375
#    email:
#        sender: 'thomas.chevily@canaltp.fr'
#        receiver: 'thomas.chevily@canaltp.fr'
#        hostname: 'localhost'
