parameters:
#    canal_tp_product.example.class: CanalTP\ProductBundle\Example

services:
#    canal_tp_product.example:
#        class: %canal_tp_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
